### ISSUE TITLE
Invalid opcode 16

### ISSUE THREAD

**Issue by EGGSYSMAN** [EldarFara/VictorianEraDev#2]
Hi, I recently downloaded the mod and tested it naturally. And when I want to enter any city, there seems to be a crash error that says "Invalid Opcode 16". What can I do to fix it?

![image](https://user-images.githubusercontent.com/39420876/148657428-1db4c59e-b378-4ed3-b7b0-a51f2ace70c1.png)
![image](https://user-images.githubusercontent.com/39420876/148657483-a7f76c3d-8e86-49bc-8ec1-135fb6de834e.png)

**Comment by EldarFara** [comment]
Opcode 16 is try_for_prop_instances operation, which was introduced in Warband version 1.161. Previous versions will not recognise it as well as some other operations mod uses. Solution is updating mb_warband.exe.
