### ISSUE TITLE
Game freeze when enter tavern or battle in new 1.0 version.

### ISSUE THREAD

**Issue by manimonji** [EldarFara/VictorianEraDev#3]
first I installed mod  version 0.5 and I played it without any problem. after some time I installed mod version 1.0 but its freeze's when you want to enter tavern marketplace or battle. I have seen this problem in some another mods. cursor changes to normal cursor .I cant see desktop but I can click desktop shortcuts. I cant use windows button or task manager to exit game. To solve this problem, I hold the power button to shutdown my laptop.

**Comment by EldarFara** [comment]
Crashes in BE have unknown reason. To be able to close game after crash, play in windowed mode.

**Comment by manimonji** [comment]
I deleted a mod named cRPG and renewed mb_warband.exe and problem fixed!!!
this new version is really good!
